apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lowry-tls
  namespace: lowry
spec:
  secretName: lowry-tls
  dnsNames:
    - lowrysimplified.giorgidevelops.space
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer