apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowry-ingress-main
  namespace: lowry
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lowrysimplified.giorgidevelops.space
      secretName: lowry-tls
  rules:
    - host: lowrysimplified.giorgidevelops.space
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lowry-api-service
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: lowry-frontend-service
                port:
                  number: 80
