apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowry-ingress-minio
  namespace: lowry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:
          - path: /minio/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lowry-minio
                port:
                  number: 9000
